CREATE DATABASE BankDB;
USE BankDB;

CREATE TABLE Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Password_ VARCHAR(10) NOT NULL,
    DNI VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Accounts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Balance DECIMAL(15, 2) NOT NULL,
    N_Cuenta VARCHAR(30) NOT NULL UNIQUE,
    CreationDate DATE NOT NULL DEFAULT (CURRENT_DATE()),
    daily_limit FLOAT DEFAULT 200,
    FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE Transaction (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Date_ DATE NOT NULL DEFAULT (CURRENT_DATE()),
    Amount DECIMAL(15, 2) NOT NULL,
    Origin_Account VARCHAR(30) NOT NULL,
    Target_Account VARCHAR(30) NOT NULL,
    FOREIGN KEY (Origin_Account) REFERENCES Accounts(N_Cuenta),
    FOREIGN KEY (Target_Account) REFERENCES Accounts(N_Cuenta)
);

